service: joke-sender
frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  environment:
    SLACKBOT_SERVICE_URL: ${env:SLACKBOT_SERVICE_URL}
    SLACKBOT_SERVICE_API_KEY: ${env:SLACKBOT_SERVICE_API_KEY}
    RANDOM_CHANNEL_ID: ${env:RANDOM_CHANNEL_ID}

plugins:
  - serverless-offline
  - serverless-ruby-layer

functions:
  app-mention-handler:
    handler: src/handler.event_handler
    events:
      - http:
          path: events
          method: post
          private: false
  send-joke:
    handler: src/handler.send_joke
    events:
      # run every Monday, Wednesday and Friday at 10:00 UTC
      - schedule: cron(00 7 ? * 2,4,6 *)