name: Build & deploy to stagging

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build_if_merged:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: staging

    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install bundler
        run: | 
          gem install bundler
          bundle -v
      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy --conceal --stage staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACKBOT_SERVICE_URL: ${{ secrets.SLACKBOT_SERVICE_URL }}
          SLACKBOT_SERVICE_API_KEY: ${{ secrets.SLACKBOT_SERVICE_API_KEY }}
          RANDOM_CHANNEL_ID: ${{ secrets.RANDOM_CHANNEL_ID }}